receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  traceBufferRedis:
    expire: 1m
    redis_url: redis:6379
    db_name: 0
    host: "0.0.0.0"
    port: 8080
    limit: 1000
    rate: 50
exporters:
  debug:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [traceBufferRedis]
      exporters: [debug]
