receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  traceBufferRedis:
exporters:
  debug:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [traceBufferRedis]
      exporters: [debug]
